# Generated by Django 4.2 on 2023-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=250)),
                ('des', models.TextField()),
            ],
        ),
    ]
